
version: '3.8'
services:
  db:
    container_name: springcrudapi
    image: postgres
    environment:
      POSTGRES_USER: clifford
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local